### ISSUE TITLE
0 reviews

### ISSUE THREAD

**Issue by GrandeSamarone** [floodoo/rating_summary#6] opened 2024-08-28 22:15 UTC
You don't accept when there is no evaluation, and what do you do in this case?
because at the beginning the user won't have any evaluation, if I start with 1 it won't be cool because the user will think they have already been evaluated

error
 Exception caught by widgets library ═══════════════════════════════════
Unsupported operation: Infinity or NaN toInt

**Comment by floodoo** [comment] 2024-08-29 05:30
I will have a look at it during the day or tomorrow. Thanks for reporting

**Comment by floodoo** [comment] 2024-08-29 07:29
What would you expect to happen?

**Comment by GrandeSamarone** [comment] 2024-08-29 09:07
> O que você esperaria que acontecesse?

If the vote count only remains at 0, the user will have 0 reviews and it is 5 stars and has no reviews until the star counts are empty.

**Comment by floodoo** [comment] 2024-08-29 09:40
I have just tried it with the example project and cannot reproduce the error. Can you please provide a code example?

![Simulator Screenshot - iPhone 15 Pro - 2024-08-29 at 11 39 40](https://github.com/user-attachments/assets/29209513-8201-4457-9893-88399f0fca51)

**Comment by GrandeSamarone** [comment] 2024-08-29 09:51
![Imagem do WhatsApp de 2024-08-29 à(s) 05 49 38_54798ecb](https://github.com/user-attachments/assets/6899c9bc-29f6-4c07-a264-082b3bf246ae)



code


RatingSummary(
                                    label: "Avaliações",
                                    counter: 0,
                                    average: 0,
                                    showAverage: true,
                                    counterFiveStars: 0,
                                    counterFourStars: 0,
                                    counterThreeStars: 0,
                                    counterTwoStars: 0,
                                    counterOneStars: 0,
                                  )
                                  
                                  **what am I doing wrong?**
                                  
                                  
                                   rating_summary: ^1.0.2+1

**Comment by floodoo** [comment] 2024-08-29 10:48
I can't reproduce the error with your code either. Can you please provide an example project (repository)?

**Comment by GrandeSamarone** [comment] 2024-08-29 11:14
https://github.com/GrandeSamarone/teste

**Comment by floodoo** [comment] 2024-08-29 12:00
Thanks for the example project. I was able to recreate it and have published a new version. It is fixed in version [^1.0.3+1](https://pub.dev/packages/rating_summary/versions/1.0.3+1)

**Closed as completed by floodoo** 2024-08-29 12:00 UTC
Labels: bug
